### PR TITLE
Add solution and project, and remove some unused code

### PR DESCRIPTION
**Pull request by drewnoakes**
Firstly, thanks for this awesome tool. It behaves exactly as I want (I have one horizontal and one vertical monitor). Using it is a pure joy 💯 

I don't like running binaries from the internet if I can help it, so sought out the source.

It would have been easier to build and run with a solution/project file, so this PR adds them.

I also removed a few few unused members, added `[STAThread]` and dispose the `Mutex` object.

### CODE REVIEW

**Comment by dale-roberts** [comment]
I'm glad that the tool works well for you, and thanks very much for taking time to contribute! Believe it or not, this is the first Pull request on my first GitHub project, so I'm going to poke and prod a bit and get familiar with the GitHub interface. I will get your suggestions merged in soon!

**Comment by drewnoakes** [comment]
No worries Dale. Take your time. If there's anything I can help with, let me know.

There are some hints on pulling the changes down locally. IIRC it's a link that says "command line instructions" somewhere near the merge button. That'll let you test it out locally.

I have some more changes on my machine that removes the last of the console stuff and puts an icon in the system tray with a context menu. Currently it just has 'exit', but I can imagine options and an about screen in there too.

The mirroring feature (mouse wraps around outer edges of monitors) might not be for everyone. That'd be a good option I think.

**Comment by drewnoakes** [comment]
I'm curious why you squash merged?

Two main points against this:

1. It edits the history so my local commits are now based upon a history that no longer exists. It means that for me to submit another PR I have to do a whole bunch more local commit wrangling to avoid including the same commits again in follow up PRs :(
2. It makes it harder to identify the source of bugs in future with tools like `git bisect`.

**Comment by dale-roberts** [comment]
Thanks for the perspective. Git, for a newcomer, seems like a bit of a minefield to me. There are so many difficult to intuit, long-ranging ramifications to every seemingly innocent decision, and everyone has their own reasons why one approach is superior to some other conflicting (no pun intended) way.

I did it “innocently” because of the touted benefits (“neater” history, so some claim, I suppose), without the insight that it makes more work for contributors (which was not mentioned in what I had read), which of course is not what I want.

Is there any way to reverse it at this point, or is it too late?

Thanks,
dale

**Comment by dale-roberts** [comment]
Drew, Hopefully I have not mucked up things beyond repair. Thank you for your patience with a Git noob, and I really appreciate your contribution, and would like to get it merged back in when it is convenient for you to make your next Pull request. In the future, I'll just do the normal merge. I just want to make sure I get this repository into a state where your next merge will work correctly.

Thanks...

**Comment by drewnoakes** [comment]
Hi Dale,

No worries. Git's not the friendliest thing to learn, but it's very flexible and powerful once you get there. And yes, you'll often hear conflicting opinions about how things should work. There's no better way than trying things out for yourself and it seems to me like you're doing a great job.

> Is there any way to reverse it at this point, or is it too late?

With Git there's always a way to fix this history :) It's actually very hard to lose stuff, so long as you can ask someone to help you get things back if you get into trouble. It's late here today now. I'll take a look soon, hopefully over the weekend.

In the meantime if you want to see what my branch contains, it's in the `notify-icon` branch of my fork of your repo:

https://github.com/drewnoakes/MouseUnSnag/tree/notify-icon

**Pull request merged**
