### PR TITLE
Add NotifyIcon and project structuring

### PR DESCRIPTION
**Pull request by drewnoakes**
This reintroduces #1 as well as some other changes.

image

There's now a context menu item that allows:
- Control over whether the mouse wraps horizontally around screens (inspired by @gillius)
- To exit the program

`Console.Write*` has been replaces with `Debug.Write*` so that debug output is available when there is no console.

A solution file and project file are added.

A `.gitignore` file is added.

The single source file is divided up into one file per class.

Some unused code is removed.

The project is bumped to allow the latest version of C# (7.3 right now).

The changes are vast, but I have tried to make each individual commit clear enough that you can still review it sensibly.

Thanks again for this tool. It works really well. With these changes I find it very easy to use.

### CODE REVIEW

**Comment by gillius** [comment]
Is it still possible to build the project from the command line without visual studio or installing anything like in the current script? For a small script like this that is kind of a cool feature of it (since I don't have a C# dev environment).

**Comment by dale-roberts** [comment]
Jason, I will incorporate Drew’s changes, then verify that is still compiles via command line. I think it should not be a problem. Will do this in the next day or so – and update the README to remain accurate.

**Comment by dale-roberts** [comment]
Drew, Thanks so much for the significant effort put into this! I will go through the changes and get them pulled in…
dale

**Comment by drewnoakes** [comment]
I don't believe there would be any problem with a command line build.

Also, once .NET Core 3 is out, it'll be nice to convert this to SDK-style projects, which means you can just type `dotnet build`. I think even `dotnet run` would work.

**Comment by GrantMoyer** [comment]
I've submitted a pull request that adds CLI flags to enable or disable all options independently. Obviously, my PR interferes with this. If this PR is accepted first and the project can still be compiled from the command line, I should be able to easily re-base my changes onto this.

**Pull request closed without merging**
